# Generated by Django 2.2 on 2019-10-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
