# Generated by Django 2.2 on 2019-10-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0002_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
